name: mobile_v2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_pagewise: ^2.0.1
  flutter_easyloading: ^3.0.3
  iconsax: ^0.0.8
  flutter_form_builder: ^7.1.1
  easy_debounce: ^2.0.2+1
  loading_indicator: ^3.0.3
  file_picker: ^4.5.1
  fluttertoast: ^8.0.9
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  crypto: ^3.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  file_saver: ^0.1.0
  intl: ^0.17.0
  email_validator: ^2.0.1
  google_sign_in: ^5.2.4
  font_awesome_flutter: ^9.2.0
  firebase_auth: ^3.3.12
  flutter_login: ^3.2.0
  google_sign_in_web: ^0.10.1+2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
